---
title: "Spiny Lobster Analysis"
author: "Pat Byrne"
date: "11/13/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,
                      message = F,
                      warning = F)
```

```{r}
library(tidyverse)
library(janitor)
library(here)
library(effsize) 
library(kableExtra) 

lob.df <- read_csv(here('lobster_abundance_sbc_lter.csv'),
                   na = '-99999') %>% 
  clean_names()
```

```{r}
lob.tidy <- lob.df %>% 
  uncount(count)

lob.ms <- lob.tidy %>% 
  count(year,site) %>% 
  mutate(
    status = case_when(
      site %in% c('NAPL','IVEE') ~ 'Marine Protected Area',
      site %in% c('AQUE','CARP','MOHK') ~ 'Unprotected Area')
    ) %>% 
  mutate(
    sitename = case_when(
      site == 'AQUE' ~ 'Arroyo Quemado',
      site == 'MOHK' ~ 'Mohawk',
      site == 'CARP' ~ 'Carpenteria',
      site == 'NAPL' ~ 'Naples',
      site == 'IVEE' ~ 'Isla Vista')
  )

```


```{r}
ggplot() +
  geom_line(data = lob.ms, aes(x = year, y = n, color = sitename, lty = status),
            lwd = 1.05) +
  scale_x_continuous(limits = c(2012,2018), 
                     expand = c(0.01,0.1)) +
  scale_y_continuous(limits = c(0,1000), 
                     expand = c(0.01,0.1),
                     breaks = seq(0,1000,200)) +
  labs(title = 'Spiny Lobster Annual Abundance',
       x = 'Year',
       y = 'Lobster Count',
       color = 'Site',
       lty = 'Site Protection Status') +
  theme(axis.line = element_line(color = 'grey50',
                                 size = 0.5),
        panel.background = element_rect(fill = 'white',
                                        colour = 'white'),
        panel.grid.major = element_line(size = 0.5, 
                                        linetype = 'solid',
                                        colour = "grey90"),
        legend.position = c(0.20,0.65),
        legend.background = element_rect(fill = 'white'),
        legend.text = element_text(size = 11),
        legend.key = element_rect(fill = NA),
        plot.title = element_text(size = 16)) 
```


```{r}

comp.df.all <- lob.tidy %>% 
  filter(
    year %in% c(2012,2018)) %>% 
  mutate(
    cyear = as.character(year)
  ) %>% 
  mutate(
    sitename = case_when(
      site == 'AQUE' ~ 'Arroyo Quemado',
      site == 'MOHK' ~ 'Mohawk',
      site == 'CARP' ~ 'Carpenteria',
      site == 'NAPL' ~ 'Naples (MPA)',
      site == 'IVEE' ~ 'Isla Vista (MPA)')
  ) %>% 
  mutate(
    sitename = factor(sitename, levels = c('Arroyo Quemado', 'Carpenteria', 'Mohawk', 'Naples (MPA)','Isla Vista (MPA)'))
  ) %>% 
  mutate(
    status = case_when(
      site %in% c('NAPL','IVEE') ~ 'Marine Protected Area',
      site %in% c('AQUE','CARP','MOHK') ~ 'Unprotected Area')
    ) 

# comp.df.mpa <- lob.df %>% 
#   filter(
#     year %in% c(2012,2018)) %>% 
#   filter(
#     site %in% c('NAPL','IVEE')
#   ) %>%
#   mutate(
#     cyear = as.character(year)
#   ) %>% 
#   mutate(
#     sitename = case_when(
#       site == 'AQUE' ~ 'Arroyo Quemado',
#       site == 'MOHK' ~ 'Mohawk',
#       site == 'CARP' ~ 'Carpenteria',
#       site == 'NAPL' ~ 'Naples',
#       site == 'IVEE' ~ 'Isla Vista')
#   )
# 
# 
# comp.df.nonmpa <- lob.df %>% 
#   filter(
#     year %in% c(2012,2018)) %>% 
#   filter(
#     site %in% c('AQUE','CARP','MOHK')
#   ) %>% 
#   mutate(
#     cyear = as.character(year)
#   ) %>% 
#   mutate(
#     sitename = case_when(
#       site == 'AQUE' ~ 'Arroyo Quemado',
#       site == 'MOHK' ~ 'Mohawk',
#       site == 'CARP' ~ 'Carpenteria',
#       site == 'NAPL' ~ 'Naples',
#       site == 'IVEE' ~ 'Isla Vista')
#   )
```

```{r}
ggplot(comp.df.all, aes(x = size_mm, group = cyear, fill = cyear)) +
  geom_density(adjust = 1.5,alpha = 0.4) +
  scale_x_continuous(limits = c(30,160), 
                     expand = c(0.01,0.1)) +
  scale_y_continuous(limits = c(0,0.045),
                     breaks = seq(0,0.08,0.04)) +
  facet_wrap(~sitename, scales = 'free') +
  annotate("text",
           x = 0.85,
           y = 0.25,
           label = "Bird nesting sites vulnerable to predation",
           size = 3) +
  theme(axis.line = element_line(color = 'grey50',
                                 size = 0.5),
        panel.background = element_rect(fill = 'white',
                                        colour = 'white'),
        panel.grid.major = element_line(size = 0.5, 
                                        linetype = 'solid',
                                        colour = "grey95"),
        legend.position = c(0.85,0.25),
        legend.background = element_blank(),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 12),
        plot.title = element_text(size = 17),
        plot.subtitle = element_text(size = 10)) +
  labs(title = 'Spiny Lobster Size Distributions',
       subtitle = 'Top Row: Unprotected Areas, Bottom Row: Marine Protected Areas',
       x = 'Estimated Size (mm)',
       y = 'Density',
       fill = 'Year') 

# ggplot(comp.df.mpa, aes(x = size_mm, group = cyear, fill = cyear)) +
#   geom_density(adjust = 1.5,alpha = 0.4) +
#   scale_x_continuous(limits = c(30,160), 
#                      expand = c(0.01,0.1)) +
#   scale_y_continuous(limits = c(0,0.045)) +
#   facet_wrap(~sitename, scales = 'free') +
#   theme(axis.line = element_line(color = 'grey50',
#                                  size = 0.5),
#         panel.background = element_rect(fill = 'white',
#                                         colour = 'white'),
#         panel.grid.major = element_line(size = 0.5, 
#                                         linetype = 'solid',
#                                         colour = "grey95"),
#         legend.background = element_blank(),
#         legend.text = element_text(size = 11),
#         plot.title = element_text(size = 16)) +
#   labs(title = 'Lobster Size Distribution - Marine Protected Areas',
#        x = 'Estimated Size (mm)',
#        y = 'Density',
#        fill = 'Year') 
# 
# ggplot(comp.df.nonmpa, aes(x = size_mm, group = cyear, fill = cyear,lty = cyear)) +
#   geom_density(adjust = 1.5,alpha = 0.4) +
#   scale_x_continuous(limits = c(30,160), 
#                      expand = c(0.01,0.1)) +
#   scale_y_continuous(limits = c(0,0.045)) +
#   facet_wrap(~sitename, scales = 'free') +
#   theme(axis.line = element_line(color = 'grey50',
#                                  size = 0.5),
#         panel.background = element_rect(fill = 'white',
#                                         colour = 'white'),
#         panel.grid.major = element_line(size = 0.5, 
#                                         linetype = 'solid',
#                                         colour = "grey95"),
#         legend.background = element_blank(),
#         legend.text = element_text(size = 11),
#         plot.title = element_text(size = 16)) +
#   labs(title = 'Lobster Size Distribution - Unprotected Areas',
#        x = 'Estimated Size (mm)',
#        y = 'Density',
#        fill = 'Year') 

```


```{r}

mpa2012 <- comp.df.all$size_mm[comp.df.all$year == 2012 & comp.df.all$status == 'Marine Protected Area']
mpa2012 <- mpa2012[!is.na(mpa2012)]


mpa2018 <- comp.df.all$size_mm[comp.df.all$year == 2018 & comp.df.all$status == 'Marine Protected Area']
mpa2018 <- mpa2018[!is.na(mpa2018)]


nonmpa2012 <- comp.df.all$size_mm[comp.df.all$year == 2012 & comp.df.all$status == 'Unprotected Area']
nonmpa2012 <- nonmpa2012[!is.na(nonmpa2012)]


nonmpa2018 <- comp.df.all$size_mm[comp.df.all$year == 2018 & comp.df.all$status == 'Unprotected Area']
nonmpa2018 <- nonmpa2018[!is.na(nonmpa2018)]

```

```{r}

means <- c(mean(mpa2012), mean(mpa2018), mean(nonmpa2012), mean(nonmpa2018))
means <- round(means,2)
stdevs <- c(sd(mpa2012), sd(mpa2018), sd(nonmpa2012), sd(nonmpa2018))
stdevs <- round(stdevs,2)
ns <- c(length(mpa2012), length(mpa2018), length(nonmpa2012), length(nonmpa2018))
ns <- as.integer(ns)
status <- c('MPA','MPA','Non-MPA','Non-MPA')
year <- c(2012,2018,2012,2018)

mpa2012.sum <- c(means[1],stdevs[1],ns[1])
mpa2018.sum <- c(means[2],stdevs[2],ns[2])
nonmpa2012.sum <- c(means[3],stdevs[3],ns[3])
nonmpa2018.sum <- c(means[4],stdevs[4],ns[4])
metrics <- c('Mean (mm)','Std. Deviation (mm)','Sample Size')

summary.df <- tibble(status, year, means, stdevs, ns)
summary.df.2 <- tibble(metrics, mpa2012.sum, mpa2018.sum, nonmpa2012.sum, nonmpa2018.sum)


summary.df %>% 
  kable(col.names = c("Protection Status", 
                     "Year", 
                     "Mean Size (mm)",
                     'St. Dev.',
                     'Sample Size')) %>% 
  kable_styling(bootstrap_options = c("striped",'bordered','condensed'),
                full_width = F,
                position = "center") %>% 
  add_header_above(c("Lobster Metrics" = 5))

summary.df.2 %>% 
  kable(col.names = c('Statistic',
                      "2012", 
                     "2018", 
                     "2012",
                     '2018'),
        align = c('l','c','c','c','c'),
        caption = 'This is a test caption') %>% 
  kable_styling(bootstrap_options = c("striped",'bordered','condensed'),
                full_width = F,
                position = "center") %>% 
  column_spec(c(1,3), border_right = T)%>% 
  add_header_above(c(" " = 1, "MPA" = 2, "Unprotected" = 2)) %>% 
  add_header_above(c("Sample Summary Statistics - Spiny Lobster Size" = 5),
                   bold = T,
                   color = 'white',
                   background = 'grey')


```


```{r}

t.2012 <- t.test(mpa2012, nonmpa2012)
d.2012 <- cohen.d(mpa2012,nonmpa2012)

t.2018 <- t.test(mpa2018, nonmpa2018)
d.2018 <- cohen.d(mpa2018, nonmpa2018)

t.mpa <- t.test(mpa2012, mpa2018)
d.mpa <- cohen.d(mpa2012, mpa2018)

t.nonmpa <- t.test(nonmpa2012, nonmpa2018)
d.nonmpa <- cohen.d(nonmpa2012, nonmpa2018)

```

